### ISSUE TITLE
Server side use

### ISSUE THREAD

**Issue by JT00** [LukeMizuhashi/apple-mapkit-js#1]
Is it possible to use this server side only? I'm trying to create a node.js rest api that would utilize the distance calculations. But, once i include require('apple-mapkit-js'); I start getting errors like "window is not defined." Is there anyway around this?

**Comment by OmarDavilaP** [comment]
> Is it possible to use this server side only? I'm trying to create a node.js rest api that would utilize the distance calculations. But, once i include require('apple-mapkit-js'); I start getting errors like "window is not defined." Is there anyway around this?

same issue here!

**Comment by LukeMizuhashi** [comment]
This is simply a copy-paste job of the binary supplied by Apple for use in browsers. So--it can be made to work server-side, but only after a lot of mocking.

One route would be to mock `window`, then mock every object the kit needs until you no longer see error messages during compile and run time.

Another route would be to include a library in your build that mocks everything one might find in the browser.

Yet another route would be to use a headless browser server-side, rather than mock.

Lastly, there might be some other library out there that offers geo-distance calculations. If it's available, one might use that rather than Apple's Mapkit.

I apologize I can't be of more help.

**Comment by LukeMizuhashi** [comment]
Something like this might get you most of the way there, if not all of the way there:
https://github.com/jsdom/jsdom
